ALTER TABLE pos ADD CONSTRAINT pos_pkey PRIMARY KEY (id);
CREATE INDEX pos_idx ON pos (pos);
ALTER TABLE word ADD CONSTRAINT word_pkey PRIMARY KEY (id);
CREATE INDEX word_idx ON word (word);
CREATE INDEX 1gram_word1_idx ON 1gram (word1_id);
CREATE INDEX 2gram_word1_idx ON 2gram (word1_id);
CREATE INDEX 2gram_word2_idx ON 2gram (word2_id);
CREATE INDEX 3gram_word1_idx ON 3gram (word1_id);
CREATE INDEX 3gram_word2_idx ON 3gram (word2_id);
CREATE INDEX 3gram_word3_idx ON 3gram (word3_id);
CREATE INDEX 4gram_word1_idx ON 4gram (word1_id);
CREATE INDEX 4gram_word2_idx ON 4gram (word2_id);
CREATE INDEX 4gram_word3_idx ON 4gram (word3_id);
CREATE INDEX 4gram_word4_idx ON 4gram (word4_id);
CREATE INDEX 5gram_word1_idx ON 5gram (word1_id);
CREATE INDEX 5gram_word2_idx ON 5gram (word2_id);
CREATE INDEX 5gram_word3_idx ON 5gram (word3_id);
CREATE INDEX 5gram_word4_idx ON 5gram (word4_id);
CREATE INDEX 5gram_word5_idx ON 5gram (word5_id);
